FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt
COPY ./src/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt 
COPY ./src/main.py  ${LAMBDA_TASK_ROOT}/main.py

# Install the specified packages
RUN pip install -r requirements.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handler" ]
